---

- name: install rpm package
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: yes

- name: install postgresql
  yum:
    name:
      - postgresql11-server
      - postgresql11-devel
      - postgresql11-contrib
      - python-psycopg2
    state: present
  become: yes

- name: initdb
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  ignore_errors: True
  environment:
    PGSETUP_INITDB_OPTIONS: "-E UTF8 --no-locale"
  become: yes

- name: pg hba
  copy:
    src: var/lib/pgsql/11/data/pg_hba.conf
    dest: /var/lib/pgsql/11/data/pg_hba.conf
  become: yes

- name: start postgresql
  systemd:
    name: postgresql-11
    state: started
    enabled: yes
    daemon-reload: yes
  become: yes

- name: create user
  postgresql_user:
    name: "{{ db_username }}"
    password: "{{ db_user_password }}"
    encrypted: yes
    state: present
  become_user: postgres
  become: yes

- name: create database
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_username }}"
  become_user: postgres
  become: yes
