---

- name: install rpm package
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: yes

- name: install postgresql
  yum:
    name:
      - postgresql11-server
      - postgresql11-devel
      - postgresql11-contrib
      - python-psycopg2
    state: present
  become: yes

- name: initdb
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  args:
    creates: /var/lib/pgsql/11
  environment:
    PGSETUP_INITDB_OPTIONS: "-E UTF8 --no-locale"
  become: yes

- name: start postgresql
  systemd:
    name: postgresql-11
    state: started
    enabled: yes
    daemon-reload: yes
  become: yes

- name: create database
  postgresql_db:
    name: sonar
  become_user: postgres
  become: yes

- name: create user
  postgresql_user:
    db: sonar
    name: sonar
    password: sonar
    encrypted: yes
    state: present
  become_user: postgres
  become: yes
